CREATE DATABASE IF NOT EXISTS hw80;

USE hw80;


CREATE TABLE IF NOT EXISTS categories(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
description TEXT(3000) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS places(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL UNIQUE,
description TEXT(3000)
);

CREATE TABLE IF NOT EXISTS items(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
categories_id INT NOT NULL,
places_id INT NOT NULL,
title VARCHAR(255) NOT NULL,
description TEXT(3000) DEFAULT NULL,
date_of_registration DATETIME,
image varchar(255) DEFAULT NULL,
INDEX product_index (title),
FOREIGN KEY (categories_id)
REFERENCES categories(id)
ON DELETE RESTRICT 
ON UPDATE CASCADE,
FOREIGN KEY (places_id)
REFERENCES places(id)
ON DELETE RESTRICT 
ON UPDATE CASCADE
);


